version: '3'

services: 

  nextcloud:
    image: nextcloud:local
    restart: always
    container_name: nextcloud
    build: .
    ports: 
      - 8080:80
    environment: 
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=p4$$W0rd
      - MYSQL_HOST=database
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin

  database:
    image: mariadb
    restart: always
    container_name: nextcloud-database
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r0oT
      - MYSQL_PASSWORD=p4$$W0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  database:
