version: '3'

services: 

  nextcloud:
    image: nathanstrobbe/nextcloud:storj-integration
    restart: always
    container_name: nextcloud
    env_file: .env.example

  database:
    image: postgres:13
    restart: always
    container_name: nextcloud-database
    volumes:
      - database:/var/lib/postgresql/data
    env_file: .env.example

volumes:
  database:
